import React from 'react';
import {rest} from 'msw';
import {setupServer} from 'msw/node';
import {renderHook} from '@testing-library/react-hooks';
import fetch from 'isomorphic-unfetch';
import {test, expect, beforeAll, afterAll} from 'vitest';
import useTrackApi from '../../features/audio-features/hooks/useTrackApi';
import QueryWrapperForTest from './reactQueryWrapperForTest';
import {SpotifyApiError} from '../../DataTypes/spotifyDataTypes';

window.fetch = fetch;

const trackInfoObj = {
  album: {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/7crPfGd2k81ekOoSqQKWWz',
        },
        href: 'https://api.spotify.com/v1/artists/7crPfGd2k81ekOoSqQKWWz',
        id: '7crPfGd2k81ekOoSqQKWWz',
        name: 'Stevie Nicks',
        type: 'artist',
        uri: 'spotify:artist:7crPfGd2k81ekOoSqQKWWz',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/0IomjU2bXFng4LQBYn7Het',
    },
    href: 'https://api.spotify.com/v1/albums/0IomjU2bXFng4LQBYn7Het',
    id: '0IomjU2bXFng4LQBYn7Het',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273af14d74d5e308ce2f3ec22f8',
        width: 640,
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02af14d74d5e308ce2f3ec22f8',
        width: 300,
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851af14d74d5e308ce2f3ec22f8',
        width: 64,
      },
    ],
    name: 'Bella Donna (2016 Remastered)',
    release_date: '1981-07-27',
    release_date_precision: 'day',
    total_tracks: 10,
    type: 'album',
    uri: 'spotify:album:0IomjU2bXFng4LQBYn7Het',
  },
  artists: [
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/7crPfGd2k81ekOoSqQKWWz',
      },
      href: 'https://api.spotify.com/v1/artists/7crPfGd2k81ekOoSqQKWWz',
      id: '7crPfGd2k81ekOoSqQKWWz',
      name: 'Stevie Nicks',
      type: 'artist',
      uri: 'spotify:artist:7crPfGd2k81ekOoSqQKWWz',
    },
  ],
  available_markets: [
    'AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW',
  ],
  disc_number: 1,
  duration_ms: 329413,
  explicit: false,
  external_ids: {
    isrc: 'USRH11604198',
  },
  external_urls: {
    spotify: 'https://open.spotify.com/track/7L3b6iaVhDVjfo52Hbvh9Z',
  },
  href: 'https://api.spotify.com/v1/tracks/7L3b6iaVhDVjfo52Hbvh9Z',
  id: '7L3b6iaVhDVjfo52Hbvh9Z',
  is_local: false,
  name: 'Edge of Seventeen - 2016 Remaster',
  popularity: 70,
  preview_url:
    'https://p.scdn.co/mp3-preview/abb0fd1b61b63ce4023c8f6dd26f5381d1ce5c42?cid=774b29d4f13844c495f206cafdad9c86',
  track_number: 6,
  type: 'track',
  uri: 'spotify:track:7L3b6iaVhDVjfo52Hbvh9Z',
};

const invalidRequestBody = {
  error: {
    status: 400,
    message: 'invalid request',
  },
};

const searchApiServer = setupServer(
  rest.get<Record<string, any>>(
    `${process.env.REACT_APP_API_BASE_URL}/v1/tracks/*`,
    (req, res, ctx) => {
      const lastPathName = req.url.pathname.split('/').slice(-1)[0];
      if (lastPathName !== '7L3b6iaVhDVjfo52Hbvh9Z') {
        return res(ctx.status(400), ctx.json(invalidRequestBody));
      }

      return res(ctx.status(200), ctx.json(trackInfoObj));
    }
  )
);

beforeAll(() => {
  searchApiServer.listen();
});
afterAll(() => {
  searchApiServer.close();
});

test('fetches the track info response with 200 status', async () => {
  const {result, waitFor} = renderHook(
    () => useTrackApi('7L3b6iaVhDVjfo52Hbvh9Z'),
    {
      wrapper: QueryWrapperForTest(),
    }
  );

  await waitFor(() => result.current.isSuccess);
  return expect(result.current.data).toEqual(trackInfoObj);
});

test('fails to fetch any track info response when the track id is invalid', async () => {
  const {result, waitFor} = renderHook(() => useTrackApi('GTAIV'), {
    wrapper: QueryWrapperForTest(),
  });

  await waitFor(() => !result.current.isFetching);
  return expect(result.current.error).toEqual(
    new SpotifyApiError(
      invalidRequestBody.error.status,
      invalidRequestBody.error.message
    )
  );
});
